export const data = [
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "firstName",
    userName: "firstname",
    userLabel: "სახელი",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "email",
    userId: "formGridEmail",
    userName: "email",
    userLabel: "მეილი",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "mobileNumber",
    userName: "mobile",
    userLabel: "მობილური",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "address",
    userName: "address",
    userLabel: "მისამართი",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "select",
    userId: "choose-country",
    userName: "country",
    userLabel: "ქვეყანა",
    option: [
      {
        key: "Georgia",
        name: "საქართვლეო",
      },
      {
        key: "USA",
        name: "აშშ",
      },
    ],
  },
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "Region",
    userName: "Region",
    userLabel: "რეგიონი",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "City",
    userName: "City",
    userLabel: "ქალაქი",
  },
  {
    xs: 6,
    sm: 6,
    inputType: "text",
    userId: "Zip",
    userName: "Zip",
    userLabel: "Zip/Code",
  },
  {
    xs: 12,
    sm: 12,
    inputType: "text-field",
    userId: "About",
    userName: "About",
    userLabel: "ზოგადი ინფორმაცია",
  },
];
