export const inputArr = [
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "firstName",
    userName: "firstname",
    userLabel: "firstname",
    error: "firstnameError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "lastName",
    userName: "lastname",
    userLabel: "lastname",
    error: "lastnameError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "select",
    userId: "choose-gender",
    userName: "gender",
    userLabel: "Choose gender",
    error: "genderError",
    option: [
      {
        key: "male",
        name: "Male",
      },
      {
        key: "female",
        name: "Female",
      },
    ],
  },
  {
    xs: 12,
    sm: 4,
    inputType: "date",
    userId: "birthDate",
    userName: "birthDay",
    userLabel: "BirthDay",
    error: "birthDayError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "text",
    userId: "PersonalId",
    userName: "personalId",
    userLabel: "personalId",
    error: "personalIdError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "mobileNumber",
    userName: "mobile",
    userLabel: "Mobile",
    error: "mobileError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "phoneNumber",
    userName: "phone",
    userLabel: "Phone",
    error: "phoneError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "email",
    userId: "formGridEmail",
    userName: "email",
    userLabel: "Email",
    error: "emailError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "password",
    userId: "formGridPassword",
    userName: "password",
    userLabel: "Password",
    error: "passwordError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "password",
    userId: "cPassword",
    userName: "cPassword",
    userLabel: "Confirm Password",
    error: "",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "text",
    userId: "department",
    userName: "department",
    userLabel: "Department",
    error: "departmentError",
  },
  {
    xs: 12,
    sm: 4,
    inputType: "select",
    userId: "status",
    userName: "status",
    userLabel: "Status",
    error: "statusError",
    option: [
      {
        key: "first",
        name: "first",
      },
      {
        key: "second",
        name: "second",
      },
    ],
  },
  {
    xs: 12,
    sm: 4,
    inputType: "date",
    userId: "startWorking",
    userName: "startWorking",
    userLabel: "StartWorking",
    error: "startWorkingError",
  },
  {
    xs: 12,
    sm: 12,
    inputType: "text",
    userId: "position",
    userName: "position",
    userLabel: "position",
    error: "positionError",
  },
];
