export const data = [
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "FirstName",
    userName: "firstname",
    userLabel: "firstname",
    variant: "outlined",
    error: "firstnameError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "LastName",
    userName: "lastname",
    userLabel: "lastname",
    variant: "outlined",
    error: "lastnameError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "Choose-gender",
    userName: "gender",
    userLabel: "Choose gender",
    variant: "outlined",
    error: "genderError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "birthDate",
    userName: "birthDay",
    userLabel: "BirthDay",
    variant: "outlined",
    error: "birthDayError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "PersonalId",
    userName: "personalId",
    userLabel: "personalId",
    variant: "outlined",
    error: "personalIdError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "mobileNumber",
    userName: "mobile",
    userLabel: "Mobile",
    variant: "outlined",
    error: "mobileError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "phoneNumber",
    userName: "phone",
    userLabel: "Phone",
    variant: "outlined",
    error: "phoneError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "email",
    userId: "formGridEmail",
    userName: "email",
    userLabel: "Email",
    variant: "outlined",
    error: "emailError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "password",
    userId: "formGridPassword",
    userName: "password",
    userLabel: "Password",
    variant: "outlined",
    error: "passwordError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "password",
    userId: "cPassword",
    userName: "cPassword",
    userLabel: "Confirm Password",
    variant: "outlined",
    error: "",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "department",
    userName: "department",
    userLabel: "Department",
    variant: "outlined",
    error: "departmentError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text",
    userId: "status",
    userName: "status",
    userLabel: "Status",
    variant: "outlined",
    error: "statusError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "date",
    userId: "startWorking",
    userName: "startWorking",
    userLabel: "StartWorking",
    variant: "outlined",
    error: "startWorkingError",
  },
  {
    xs: 12,
    sm: 6,
    inputType: "text-area",
    userId: "position",
    userName: "position",
    userLabel: "position",
    variant: "outlined",
    error: "positionError",
  },
];
