export const gatewayData = [
  {
    checked: false,
    label: "გეითვეი 1",
    value: "d-34845",
    model: "d-34845",
    status: 1,
    group: [],
    device: [
      {
        type: "fan coil",
        name: "სენსორი 1",
        id: "1",
        value: 4,
        status: "active",
        variables: [
          {
            value: 22441,
            temperature: 22,
            name: "ცვლადი 1",
            id: "1",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            speed: ["low", "middle", "high"],
          },
        ],
      },
    ],
  },
  {
    checked: false,
    label: "გეითვეი 2",
    value: "d-71345",
    model: "d-71345",
    status: 0,
    group: [],
    device: [
      {
        type: "midea vrf",
        name: "სენსორი 2",
        value: "27",
        id: 2,
        status: "notActive",
        variables: [
          {
            value: 2244,
            temperature: 22,
            name: "ცვლადი 3",
            id: "3",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
      {
        type: "midea vrf",
        name: "სენსორი 3",
        value: "17",
        id: 3,
        status: "removed",
        variables: [
          {
            value: "28",
            temperature: 22,
            name: "ცვლადი 5",
            id: "5",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
      {
        type: "midea vrf",
        name: "სენსორი 4",
        value: "27",
        id: 4,
        status: "removed",
        variables: [
          {
            value: 2244,
            temperature: 22,
            name: "ცვლადი 6",
            id: "6",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
      {
        type: "midea vrf",
        name: "სენსორი 5",
        value: "27",
        id: 7,
        status: "removed",
        variables: [
          {
            value: 2244,
            temperature: 22,
            name: "ცვლადი 7",
            id: "7",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
      {
        type: "midea vrf",
        name: "სენსორი 8",
        value: "27",
        id: 8,
        status: "removed",
        variables: [
          {
            value: 2244,
            temperature: 22,
            name: "ცვლადი 8",
            id: "8",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
      {
        type: "midea vrf",
        name: "სენსორი 9",
        value: "27",
        id: 9,
        status: "removed",
        variables: [
          {
            value: 2244,
            temperature: 22,
            name: "ცვლადი 9",
            id: "9",
            status: "active",
            mode: ["winter", "summer", "fan", "off"],
            swing: ["closed", "open"],
          },
        ],
      },
    ],
  },
  // {
  //   checked: false,
  //   label: "გეითვეი 3",
  //   value: "d-143145",
  //   model: "d-143145",
  //   status: 1,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 3",
  //       value: "2",
  //       id: "3",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 2200,
  //           temperature: 22,
  //           name: "ცვლადი 3",
  //           id: "3",
  //           status: "active",
  //         },
  //         {
  //           value: 2223,
  //           temperature: 22,
  //           name: "ცვლადი 7",
  //           id: "7",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 4",
  //   value: "d-44345",
  //   model: "d-44345",
  //   status: 1,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 4",
  //       id: "4",
  //       value: "2",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 142,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 82,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 5",
  //   value: "d-45345",
  //   model: "d-45345",
  //   status: 0,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 5",
  //       value: "1",
  //       id: "5",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 2392,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 3327,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //     {
  //       name: "სენსორი 15",
  //       value: "2",
  //       id: "15",
  //       status: "removed",
  //       variables: [
  //         {
  //           value: 732,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 342,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 6",
  //   value: "d-3445",
  //   model: "d-3445",
  //   status: 1,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 6",
  //       value: "2",
  //       id: "6",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 3322,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 23232,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 7",
  //   value: "d-43255",
  //   model: "d-43255",
  //   status: 0,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 7",
  //       value: "2",
  //       id: "7",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 229,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 662,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //     {
  //       name: "სენსორი 16",
  //       id: "16",
  //       value: "2",
  //       status: "notActive",
  //       variables: [
  //         {
  //           value: 262,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 2162,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 8",
  //   value: "d-42134545",
  //   model: "d-42134545",
  //   status: 1,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 8",
  //       value: "2",
  //       id: "8",
  //       status: "active",
  //       variables: [
  //         {
  //           value: 2362,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 26262,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 9",
  //   value: "d-455353",
  //   model: "d-455353",
  //   status: 1,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 9",
  //       value: "1",
  //       id: "9",
  //       status: "notActive",
  //       variables: [
  //         {
  //           value: 6232,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 6822,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //     {
  //       name: "სენსორი 12",
  //       id: "12",
  //       value: "2",
  //       status: "active",
  //     },
  //     {
  //       name: "სენსორი 13",
  //       value: "3",
  //       id: "13",
  //       status: "removed",
  //     },
  //   ],
  // },
  // {
  //   checked: false,
  //   label: "გეითვეი 10",
  //   value: "d-4355",
  //   model: "d-4355",
  //   status: 0,
  //   group: [],
  //   device: [
  //     {
  //       name: "სენსორი 10",
  //       value: "2",
  //       id: "10",
  //       status: "notActive",
  //       variables: [
  //         {
  //           value: 66272,
  //           temperature: 22,
  //           name: "ცვლადი 1",
  //           id: "1",
  //           status: "active",
  //         },
  //         {
  //           value: 69622,
  //           temperature: 22,
  //           name: "ცვლადი 2",
  //           id: "2",
  //           status: "not active",
  //         },
  //       ],
  //     },
  //     {
  //       name: "სენსორი 11",
  //       value: "2",
  //       id: "11",
  //       status: "removed",
  //     },
  //   ],
  // },
];
